# Generated by Django 5.2.7 on 2025-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('reps_sets', models.CharField(max_length=50)),
                ('exercise_type', models.CharField(max_length=50)),
                ('bodypart', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
