# Generated by Django 5.2.7 on 2025-10-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exercise_type', models.CharField(max_length=255)),
                ('bodypart', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='url',
            old_name='exercise',
            new_name='title',
        ),
    ]
